export enum ImageActionTypes {
   MOVE_IMAGE,
   DELETE_IMAGE,
   INSERT_IMAGE_AFTER,
   UPDATE_IMAGE,
   BUNDLE_START,
   BUNDLE_COMPLETE,
   FETCH_IMAGE,
   FETCH_IMAGE_COMPLETE,
   FETCH_IMAGE_ERROR,
}
